# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 9) do

  create_table "fact_names", :force => true do |t|
    t.column "name",       :string
    t.column "updated_at", :datetime
  end

  add_index "fact_names", ["id"], :name => "index_fact_names_on_id"
  add_index "fact_names", ["name"], :name => "index_fact_names_on_name"

  create_table "fact_values", :force => true do |t|
    t.column "value",        :text,     :null => false
    t.column "fact_name_id", :integer,  :null => false
    t.column "host_id",      :integer,  :null => false
    t.column "updated_at",   :datetime
  end

  add_index "fact_values", ["id"], :name => "index_fact_values_on_id"
  add_index "fact_values", ["fact_name_id"], :name => "index_fact_values_on_fact_name_id"
  add_index "fact_values", ["host_id"], :name => "index_fact_values_on_host_id"

  create_table "hosts", :force => true do |t|
    t.column "name",            :string,   :null => false
    t.column "ip",              :string
    t.column "last_compile",    :datetime
    t.column "last_freshcheck", :datetime
    t.column "last_report",     :datetime
    t.column "updated_at",      :datetime
    t.column "source_file_id",  :integer
  end

  add_index "hosts", ["id"], :name => "index_hosts_on_id"
  add_index "hosts", ["source_file_id"], :name => "index_hosts_on_source_file_id"
  add_index "hosts", ["name"], :name => "index_hosts_on_name"

  create_table "param_names", :force => true do |t|
    t.column "name",       :string
    t.column "updated_at", :datetime
  end

  add_index "param_names", ["id"], :name => "index_param_names_on_id"
  add_index "param_names", ["name"], :name => "index_param_names_on_name"

  create_table "param_values", :force => true do |t|
    t.column "value",         :text,     :null => false
    t.column "param_name_id", :integer,  :null => false
    t.column "line",          :integer
    t.column "resource_id",   :integer
    t.column "updated_at",    :datetime
  end

  add_index "param_values", ["id"], :name => "index_param_values_on_id"
  add_index "param_values", ["param_name_id"], :name => "index_param_values_on_param_name_id"
  add_index "param_values", ["resource_id"], :name => "index_param_values_on_resource_id"

  create_table "puppet_tags", :force => true do |t|
    t.column "name",       :string
    t.column "updated_at", :datetime
  end

  add_index "puppet_tags", ["id"], :name => "index_puppet_tags_on_id"

  create_table "resource_tags", :force => true do |t|
    t.column "resource_id",   :string
    t.column "puppet_tag_id", :integer
    t.column "updated_at",    :datetime
  end

  add_index "resource_tags", ["id"], :name => "index_resource_tags_on_id"
  add_index "resource_tags", ["resource_id"], :name => "index_resource_tags_on_resource_id"
  add_index "resource_tags", ["puppet_tag_id"], :name => "index_resource_tags_on_puppet_tag_id"

  create_table "resources", :force => true do |t|
    t.column "title",          :text,     :null => false
    t.column "restype",        :string,   :null => false
    t.column "host_id",        :integer
    t.column "source_file_id", :integer
    t.column "exported",       :boolean
    t.column "line",           :integer
    t.column "updated_at",     :datetime
  end

  add_index "resources", ["id"], :name => "index_resources_on_id"
  add_index "resources", ["host_id"], :name => "index_resources_on_host_id"
  add_index "resources", ["source_file_id"], :name => "index_resources_on_source_file_id"
  add_index "resources", ["restype", "title"], :name => "typentitle"

  create_table "source_files", :force => true do |t|
    t.column "filename",   :string
    t.column "path",       :string
    t.column "updated_at", :datetime
  end

  add_index "source_files", ["id"], :name => "index_source_files_on_id"
  add_index "source_files", ["filename"], :name => "index_source_files_on_filename"

end
